### ISSUE TITLE
sync testnet daemon

### ISSUE THREAD

**Issue by minhnt812018** [loki-project/loki#66] opened 2018-05-07 03:04 UTC
Hi,

I try to sync testnet daemon, but got error, please help. Thank!
![image](https://user-images.githubusercontent.com/37006960/39683122-fcb1d8c8-51dd-11e8-9fb5-6d28eb932b5a.png)

**Comment by jcktm** [comment] 2018-05-07 03:52
Duplicate of #61

**Comment by jcktm** [comment] 2018-05-07 03:53
This is fixed on dev branch now

**Closed** 2018-05-23 01:07 UTC
