### ISSUE TITLE
Export and import key images broken for view key

### ISSUE THREAD

**Issue by tokerato** [loki-project/loki#357] opened 2018-12-02 15:37 UTC
For 2 wallets recently updated to 2.0 (from 1.0.4) && 2 view keys/wallets recently updated to 2.0 (from 1.0.4)

For wallet #1 view key #1 - Key image import height key image registered at block height #14960315599309978599 : "Signed key images imported to height 14960315599309978599"

For wallet #2 view key #2 "Signed key images imported to height 7742873959489039251, 0.000000000 spent, 0.000000000 unspent"

On both view wallets - balance was incorrect as well as export transfer following import of new key images.

**Comment by msgmaxim** [comment] 2018-12-03 22:48
I'm not able to reproduce this error. Were the images exported using 2.0 as well? Would you be able to provide more information?

**Comment by tokerato** [comment] 2018-12-04 01:05
In short - yes images were exported using 2.0 as well.

In detail: I tested this on 2 'main' wallets (both originally on 1.0.4 / recently updated to 2.0) Ubuntu 16.04 - and out of them created 2 separate view keys/view wallets hosted on a different machine (both originally on 1.0.4 / recently updated to 2.0) Ubuntu 16.04.

On September / version 1.0.4 from the 'main' wallet(s)- an export was done using export_key_images <filename> 
Once for each 'main wallet' - so two key images were generated for 2 'main' wallets.

Key images were imported to each respective wallet (running 1.0.4) using import_key_images <filename>.

On September version 1.0.4 - this worked on both occasions.

In the last week both main 'wallets' & viewing 'wallets' were updated to 2.0. The same process was repeated and the block heights on import have been invalid as per the output pasted in my initial comment. As expected - the balance & export transfers have also been wrong.

I have also tested 'rescan_spent' prior to export/import - and this hasn't fixed the issue.

**Comment by KeeJef** [comment] 2018-12-05 04:51
We have merged a change into release https://github.com/loki-project/loki/releases/tag/v2.0.1 please let 
that exports all key images by default let us know if you are still experiencing this issue with the fix in place

**Comment by tokerato** [comment] 2018-12-17 04:30
The balance command is now showing the correct balance between two wallets but export_transfers 0 <key image blockheight> is still incorrect.

Steps:

1) rescan_spent on main wallet
2) export_key_images <filename> on main wallet
3) import_key_images <filename> on view wallet
4) rescan_spent on view wallet
5) export_transfers 0 <max blockheight of keyimage>

-- the running balance is ~ 3x the actual balance and is wrong throughout.
This could be replicated in the past if I ever tried to export transfers using a blockheight > max blockheight of key image.
This appears unrelated to https://github.com/loki-project/loki/issues/370

**Comment by tokerato** [comment] 2019-01-10 04:11
Auditors have been requesting for an update for this - can we please look at pushing in an earlier bug fix.

**Comment by tokerato** [comment] 2019-01-16 04:14
Following the update 2.0.3 - there is now an error when I export transfers ( bug fix did not work / an output file is generated but the running balance is wrong):

[wallet XXXXXX]: export_transfers
Error: Warning: Unhandled pay type, this is most likely a developer error, please report it to the Loki developers.
Error: Warning: Unhandled pay type, this is most likely a developer error, please report it to the Loki developers.

**Comment by Doy-lee** [comment] 2019-01-16 05:20
Since there were various problems in previous versions the cached wallet data may be in an invalid state, in particular this case with exporting key image behaviour changing and saving various state into the wallet cache.. This can be remedied by rescan_bc so it regenerates the data it needs using the new code.

**Comment by tokerato** [comment] 2019-01-16 05:33
The issue was resolved after running rescan_bc

Thanks.

**Closed** 2019-01-16 05:45 UTC
