### ISSUE TITLE
Build Static Windows

### ISSUE THREAD

**Issue by Arielony** [loki-project/loki#324] opened 2018-11-17 16:40 UTC
I've just compiled dev branch on windows (because i need it on that OS) with make release-static-win64 order, and when it finishes shows me this message because it cannot get all the .dll 

"the program can't start because libzmq.dll is missing from your computer"

![issue](https://user-images.githubusercontent.com/24939958/48663615-74685a00-ea71-11e8-9ba7-a70baa0d0a3c.png)

**Comment by majestrate** [comment] 2018-11-17 18:07
did you cross compile it from another os?

**Comment by equisde** [comment] 2018-11-17 18:14
i have the same issue i cross compiled from windows on  mingw following the guide on the readme

**Comment by saargospa** [comment] 2018-11-17 19:17
I followed the tutorial for mingw on Windows 7 @majestrate

**Comment by Arielony** [comment] 2018-11-17 19:19
I followed the tutorial for mingw on Windows 7.

**Comment by Doy-lee** [comment] 2018-11-19 02:40
I'm having troubles reproducing this on a stock Windows VM following the guide. The only missing step I had was

```
git submodule update --recursive
```

And that's because I cloned master first and then checked out dev which contains some new submodule data so it needs to update the git tree. Your steps, build logs, build environment would be ideal to figuring this out.

Adding this to your CMakeLists.txt in the root directory will print the ZMQ lib it's linking against.

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index e430b976..8f48c8ca 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -984,6 +984,7 @@ endif()
 if(SODIUM_LIBRARY)
   set(ZMQ_LIB "${ZMQ_LIB};${SODIUM_LIBRARY}")
 endif()
+message(STATUS "!!!!!!!!!!!!!!!!!!!!!!!!!Found ZMQ at ${ZMQ_LIB}")

 add_subdirectory(contrib)
 add_subdirectory(src)
```

To which mine prints

```
-- !!!!!!!!!!!!!!!!!!!!!!!!!Found ZMQ at C:/msys64/mingw64/lib/libzmq.a;C:/msys64/mingw64/lib/libsodium.a
```

**Comment by Arielony** [comment] 2018-11-19 04:12
Sure.. please see it https://pastebin.com/LaHPizjP

**Comment by Doy-lee** [comment] 2018-11-19 04:47
The build log has no mention of blockchain_ancestry which is a new executable or hidapi which indicates you're building an old version of the repository.

So you're not building the latest commit on dev and it's also linking against the DLL so it requires it at runtime. Update the git repository and try again.

**Comment by KeeJef** [comment] 2018-12-05 04:53
Will close this if issue has been resolved

**Closed** 2019-02-08 06:47 UTC
